Fix `#find_by`
```ruby
  1) Model sample #find_by finds the record
     Failure/Error: collector << quote_table_name(o.relation.table_alias || o.relation.name) << '.' unless collector.value.start_with?('DELETE FROM ') || collector.value.include?(' UPDATE ')

     NoMethodError:
       undefined method `start_with?' for [["SELECT", " "], []]:Array
     # ./lib/arel/visitors/clickhouse.rb:19:in `visit_Arel_Attributes_Attribute'
     # ./spec/single/model_spec.rb:114:in `block (4 levels) in <top (required)>'
     # ./spec/spec_helper.rb:29:in `block (2 levels) in <top (required)>'
```