Added support for Rails 6.1.0; (#35)
* Added support for Rails 6.1.0;

* fix the TypeCaster is_view which changed in 6.1

* fix NoMethodError: undefined method 'table_options' in schema_creation for Rails 6.1

* fix getting options for creating a table for rails 6.1

* using hash with indifferent access for task configuration

* Fixing Ruby 3 keyword arguments in SchemaStatements#create_table_definition

* fixing migration column argument expansion

* fix getting default migration path if not configured in Rails